// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as http$0 from "../../../github.com/qtgolang/SunnyNet/src/http/models.js";

export class Auth {
    /**
     * Creates a new Auth instance.
     * @param {Partial<Auth>} [$$source = {}] - The source object to create the Auth.
     */
    constructor($$source = {}) {
        if (!("User" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["User"] = "";
        }
        if (!("Pass" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Pass"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Auth instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Auth}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Auth(/** @type {Partial<Auth>} */($$parsedSource));
    }
}

export class AuthenticationInfo {
    /**
     * Creates a new AuthenticationInfo instance.
     * @param {Partial<AuthenticationInfo>} [$$source = {}] - The source object to create the AuthenticationInfo.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("User" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["User"] = "";
        }
        if (!("Pass" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Pass"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthenticationInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AuthenticationInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuthenticationInfo(/** @type {Partial<AuthenticationInfo>} */($$parsedSource));
    }
}

export class CertInfo {
    /**
     * Creates a new CertInfo instance.
     * @param {Partial<CertInfo>} [$$source = {}] - The source object to create the CertInfo.
     */
    constructor($$source = {}) {
        if (!("DoMain" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["DoMain"] = "";
        }
        if (!("Path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Path"] = "";
        }
        if (!("Pass" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Pass"] = "";
        }
        if (!("Note" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Note"] = "";
        }
        if (!("Role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Role"] = "";
        }
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("LoadOk" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["LoadOk"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CertInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CertInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CertInfo(/** @type {Partial<CertInfo>} */($$parsedSource));
    }
}

export class DoHTTPRequestInfo {
    /**
     * Creates a new DoHTTPRequestInfo instance.
     * @param {Partial<DoHTTPRequestInfo>} [$$source = {}] - The source object to create the DoHTTPRequestInfo.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("header" in $$source)) {
            /**
             * @member
             * @type {http$0.Header}
             */
            this["header"] = {};
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("bodyType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bodyType"] = "";
        }
        if (!("outTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["outTime"] = 0;
        }
        if (!("redirect" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["redirect"] = false;
        }
        if (!("disguise" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["disguise"] = false;
        }
        if (!("proxyIP" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxyIP"] = "";
        }
        if (!("Language" in $$source)) {
            /**
             * httpDebug调试工具，生成代码时使用
             * @member
             * @type {string}
             */
            this["Language"] = "";
        }
        if (!("Type" in $$source)) {
            /**
             * httpDebug调试工具，生成代码时使用
             * @member
             * @type {string}
             */
            this["Type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DoHTTPRequestInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DoHTTPRequestInfo}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("header" in $$parsedSource) {
            $$parsedSource["header"] = $$createField2_0($$parsedSource["header"]);
        }
        return new DoHTTPRequestInfo(/** @type {Partial<DoHTTPRequestInfo>} */($$parsedSource));
    }
}

export class ProxyWayInfo {
    /**
     * Creates a new ProxyWayInfo instance.
     * @param {Partial<ProxyWayInfo>} [$$source = {}] - The source object to create the ProxyWayInfo.
     */
    constructor($$source = {}) {
        if (!("State" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["State"] = "";
        }
        if (!("Note" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Note"] = "";
        }
        if (!("URL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["URL"] = "";
        }
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyWayInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProxyWayInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProxyWayInfo(/** @type {Partial<ProxyWayInfo>} */($$parsedSource));
    }
}

export class ReplaceBodyInfo {
    /**
     * Creates a new ReplaceBodyInfo instance.
     * @param {Partial<ReplaceBodyInfo>} [$$source = {}] - The source object to create the ReplaceBodyInfo.
     */
    constructor($$source = {}) {
        if (!("Type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Type"] = "";
        }
        if (!("Lod" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Lod"] = "";
        }
        if (!("New" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["New"] = "";
        }
        if (!("Source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Source"] = "";
        }
        if (!("Note" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Note"] = "";
        }
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("State" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["State"] = "";
        }
        if (!("Ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReplaceBodyInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReplaceBodyInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReplaceBodyInfo(/** @type {Partial<ReplaceBodyInfo>} */($$parsedSource));
    }
}

export class ReplaceHostInfo {
    /**
     * Creates a new ReplaceHostInfo instance.
     * @param {Partial<ReplaceHostInfo>} [$$source = {}] - The source object to create the ReplaceHostInfo.
     */
    constructor($$source = {}) {
        if (!("Lod" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Lod"] = "";
        }
        if (!("New" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["New"] = "";
        }
        if (!("Note" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Note"] = "";
        }
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReplaceHostInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReplaceHostInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReplaceHostInfo(/** @type {Partial<ReplaceHostInfo>} */($$parsedSource));
    }
}

export class ToolsInfo {
    /**
     * Creates a new ToolsInfo instance.
     * @param {Partial<ToolsInfo>} [$$source = {}] - The source object to create the ToolsInfo.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Icon"] = "";
        }
        if (!("File" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["File"] = "";
        }
        if (!("Args" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Args"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolsInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolsInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolsInfo(/** @type {Partial<ToolsInfo>} */($$parsedSource));
    }
}

// Private type creation functions
var $$createType0 = /** @type {(...args: any[]) => any} */(function $$initCreateType0(...args) {
    if ($$createType0 === $$initCreateType0) {
        $$createType0 = $$createType2;
    }
    return $$createType0(...args);
});
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Map($Create.Any, $$createType1);
