// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class EncodingInfo {
    /**
     * Creates a new EncodingInfo instance.
     * @param {Partial<EncodingInfo>} [$$source = {}] - The source object to create the EncodingInfo.
     */
    constructor($$source = {}) {
        if (!("children" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["children"] = [];
        }
        if (!("Data" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EncodingInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EncodingInfo}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField0_0($$parsedSource["children"]);
        }
        return new EncodingInfo(/** @type {Partial<EncodingInfo>} */($$parsedSource));
    }
}

export class EncryptionInfo {
    /**
     * Creates a new EncryptionInfo instance.
     * @param {Partial<EncryptionInfo>} [$$source = {}] - The source object to create the EncryptionInfo.
     */
    constructor($$source = {}) {
        if (!("children" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["children"] = [];
        }
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("iv" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["iv"] = "";
        }
        if (!("ivType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ivType"] = "";
        }
        if (!("keyType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["keyType"] = "";
        }
        if (!("isEncrypt" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isEncrypt"] = false;
        }
        if (!("SM2Mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SM2Mode"] = "";
        }
        if (!("Data" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EncryptionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EncryptionInfo}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField0_0($$parsedSource["children"]);
        }
        return new EncryptionInfo(/** @type {Partial<EncryptionInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
