// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as http$0 from "../../../github.com/qtgolang/SunnyNet/src/http/models.js";

export class HttpSession {
    /**
     * Creates a new HttpSession instance.
     * @param {Partial<HttpSession>} [$$source = {}] - The source object to create the HttpSession.
     */
    constructor($$source = {}) {
        if (!("Theology" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Theology"] = 0;
        }
        if (!("Ico" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Ico"] = "";
        }
        if (!("Request" in $$source)) {
            /**
             * @member
             * @type {HttpSessionRequest}
             */
            this["Request"] = (new HttpSessionRequest());
        }
        if (!("Response" in $$source)) {
            /**
             * @member
             * @type {HttpSessionResponse}
             */
            this["Response"] = (new HttpSessionResponse());
        }
        if (!("Error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Error"] = "";
        }
        if (!("State" in $$source)) {
            /**
             * 请求状态
             * @member
             * @type {number}
             */
            this["State"] = 0;
        }
        if (!("RecLength" in $$source)) {
            /**
             * 接收数据长度
             * @member
             * @type {number}
             */
            this["RecLength"] = 0;
        }
        if (!("SenLength" in $$source)) {
            /**
             * 发送数据长度
             * @member
             * @type {number}
             */
            this["SenLength"] = 0;
        }
        if (!("Note" in $$source)) {
            /**
             * 添加的注释
             * @member
             * @type {string}
             */
            this["Note"] = "";
        }
        if (!("UserName" in $$source)) {
            /**
             * 身份验证账号
             * @member
             * @type {string}
             */
            this["UserName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HttpSession instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HttpSession}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Request" in $$parsedSource) {
            $$parsedSource["Request"] = $$createField2_0($$parsedSource["Request"]);
        }
        if ("Response" in $$parsedSource) {
            $$parsedSource["Response"] = $$createField3_0($$parsedSource["Response"]);
        }
        return new HttpSession(/** @type {Partial<HttpSession>} */($$parsedSource));
    }
}

export class HttpSessionRequest {
    /**
     * Creates a new HttpSessionRequest instance.
     * @param {Partial<HttpSessionRequest>} [$$source = {}] - The source object to create the HttpSessionRequest.
     */
    constructor($$source = {}) {
        if (!("Method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Method"] = "";
        }
        if (!("Url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Url"] = "";
        }
        if (!("ClientIP" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ClientIP"] = "";
        }
        if (!("Time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Time"] = "";
        }
        if (!("ProcessName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ProcessName"] = "";
        }
        if (!("Proto" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Proto"] = "";
        }
        if (!("Header" in $$source)) {
            /**
             * @member
             * @type {http$0.Header}
             */
            this["Header"] = {};
        }
        if (!("BodyLength" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["BodyLength"] = 0;
        }
        if (!("IsMaxLength" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsMaxLength"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HttpSessionRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HttpSessionRequest}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Header" in $$parsedSource) {
            $$parsedSource["Header"] = $$createField6_0($$parsedSource["Header"]);
        }
        return new HttpSessionRequest(/** @type {Partial<HttpSessionRequest>} */($$parsedSource));
    }
}

export class HttpSessionResponse {
    /**
     * Creates a new HttpSessionResponse instance.
     * @param {Partial<HttpSessionResponse>} [$$source = {}] - The source object to create the HttpSessionResponse.
     */
    constructor($$source = {}) {
        if (!("Time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Time"] = "";
        }
        if (!("Code" in $$source)) {
            /**
             * 响应状态码
             * @member
             * @type {string}
             */
            this["Code"] = "";
        }
        if (!("State" in $$source)) {
            /**
             * 响应状态文本
             * @member
             * @type {string}
             */
            this["State"] = "";
        }
        if (!("Type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Type"] = "";
        }
        if (!("Length" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Length"] = 0;
        }
        if (!("Proto" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Proto"] = "";
        }
        if (!("Header" in $$source)) {
            /**
             * @member
             * @type {http$0.Header}
             */
            this["Header"] = {};
        }
        if (!("Body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Body"] = "";
        }
        if (!("ResponseType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ResponseType"] = "";
        }
        if (!("BodyLength" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["BodyLength"] = 0;
        }
        if (!("IsMaxLength" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsMaxLength"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HttpSessionResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HttpSessionResponse}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Header" in $$parsedSource) {
            $$parsedSource["Header"] = $$createField6_0($$parsedSource["Header"]);
        }
        if ("Body" in $$parsedSource) {
            $$parsedSource["Body"] = $$createField7_0($$parsedSource["Body"]);
        }
        return new HttpSessionResponse(/** @type {Partial<HttpSessionResponse>} */($$parsedSource));
    }
}

export class Insert {
    /**
     * Creates a new Insert instance.
     * @param {Partial<Insert>} [$$source = {}] - The source object to create the Insert.
     */
    constructor($$source = {}) {
        if (!("IsHTTP" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsHTTP"] = false;
        }
        if (!("Method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Method"] = "";
        }
        if (!("URL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["URL"] = "";
        }
        if (!("ProcessName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ProcessName"] = "";
        }
        if (!("ClientIP" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ClientIP"] = "";
        }
        if (!("Theology" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Theology"] = 0;
        }
        if (!("Time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Time"] = "";
        }
        if (!("Ico" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Ico"] = "";
        }
        if (!("Filter" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Filter"] = false;
        }
        if (!("UserName" in $$source)) {
            /**
             * 身份验证的账号
             * @member
             * @type {string}
             */
            this["UserName"] = "";
        }
        if (!("BreakMode" in $$source)) {
            /**
             * 断点模式
             * @member
             * @type {number}
             */
            this["BreakMode"] = 0;
        }
        if (!("GuaranteeDisplay" in $$source)) {
            /**
             * 保证显示此消息
             * @member
             * @type {boolean}
             */
            this["GuaranteeDisplay"] = false;
        }
        if (!("RemoteAddress" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["RemoteAddress"] = "";
        }
        if (!("Host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Host"] = "";
        }
        if (!("Note" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Note"] = "";
        }
        if (!("State" in $$source)) {
            /**
             * 状态 已连接/已断开
             * @member
             * @type {string}
             */
            this["State"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Insert instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Insert}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Insert(/** @type {Partial<Insert>} */($$parsedSource));
    }
}

export class UpdateSocketStream {
    /**
     * Creates a new UpdateSocketStream instance.
     * @param {Partial<UpdateSocketStream>} [$$source = {}] - The source object to create the UpdateSocketStream.
     */
    constructor($$source = {}) {
        if (!("Theology" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Theology"] = 0;
        }
        if (!("MessageId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["MessageId"] = 0;
        }
        if (!("WebsocketType" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["WebsocketType"] = 0;
        }
        if (!("Length" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Length"] = 0;
        }
        if (!("IsSend" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsSend"] = false;
        }
        if (!("IsActiveSend" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsActiveSend"] = false;
        }
        if (!("Time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Time"] = "";
        }
        if (!("Body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Body"] = "";
        }
        if (!("Filter" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Filter"] = false;
        }
        if (!("IsClose" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsClose"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateSocketStream instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateSocketStream}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateSocketStream(/** @type {Partial<UpdateSocketStream>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = HttpSessionRequest.createFrom;
const $$createType1 = HttpSessionResponse.createFrom;
var $$createType2 = /** @type {(...args: any[]) => any} */(function $$initCreateType2(...args) {
    if ($$createType2 === $$initCreateType2) {
        $$createType2 = $$createType4;
    }
    return $$createType2(...args);
});
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $Create.Map($Create.Any, $$createType3);
