// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * MCPMsg 与前端 WebView 通信的消息结构
 */
export class McpMsg {
    /**
     * Creates a new McpMsg instance.
     * @param {Partial<McpMsg>} [$$source = {}] - The source object to create the McpMsg.
     */
    constructor($$source = {}) {
        if (!("page" in $$source)) {
            /**
             * 页面名（例如 Main）
             * @member
             * @type {string}
             */
            this["page"] = "";
        }
        if (!("tag" in $$source)) {
            /**
             * 消息类型（例如 home/SystemProxy）
             * @member
             * @type {string}
             */
            this["tag"] = "";
        }
        if (!("msg" in $$source)) {
            /**
             * 请求内容
             * @member
             * @type {string}
             */
            this["msg"] = "";
        }
        if (!("res" in $$source)) {
            /**
             * 回包内容
             * @member
             * @type {string}
             */
            this["res"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * 请求ID（用于匹配请求/回包）
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new McpMsg instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {McpMsg}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new McpMsg(/** @type {Partial<McpMsg>} */($$parsedSource));
    }
}
