// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * A Header represents the key-value pairs in an HTTP header.
 * 
 * The keys should be in canonical form, as returned by
 * CanonicalHeaderKey.
 * @typedef {$models.Header} Header
 */
