// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * A Header represents the key-value pairs in an HTTP header.
 * 
 * The keys should be in canonical form, as returned by
 * CanonicalHeaderKey.
 * @typedef {{ [_ in string]?: string[] }} Header
 */
