// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ProcessesInfo {
    /**
     * Creates a new ProcessesInfo instance.
     * @param {Partial<ProcessesInfo>} [$$source = {}] - The source object to create the ProcessesInfo.
     */
    constructor($$source = {}) {
        if (!("Pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Pid"] = 0;
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessesInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProcessesInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcessesInfo(/** @type {Partial<ProcessesInfo>} */($$parsedSource));
    }
}
