// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallDo(arg1:Array<any>):Promise<void>;

export function Do(arg1:any):Promise<any>;
