// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallDo(arg1) {
  return window['go']['main']['App']['CallDo'](arg1);
}

export function Do(arg1) {
  return window['go']['main']['App']['Do'](arg1);
}
