// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as Config$0 from "./Config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as Session$0 from "./Session/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as Tools$0 from "./Tools/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as DebugTools$0 from "./Tools/DebugTools/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mcp$0 from "./mcp/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function AppCheckSunnyNet() {
    return $Call.ByID(279548144);
}

/**
 * AppDeleteSession 删除指定会话
 * @param {number[]} tid
 * @returns {$CancellablePromise<void>}
 */
export function AppDeleteSession(tid) {
    return $Call.ByID(2806637319, tid);
}

/**
 * AppDisconnectTCPRequest 断开选中的TCP请求
 * @param {number[]} id
 * @returns {$CancellablePromise<void>}
 */
export function AppDisconnectTCPRequest(id) {
    return $Call.ByID(2093392620, id);
}

/**
 * @param {DebugTools$0.EncodingInfo} obj
 * @returns {$CancellablePromise<string>}
 */
export function AppEncodingCall(obj) {
    return $Call.ByID(1321165611, obj).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * @param {DebugTools$0.EncryptionInfo} obj
 * @returns {$CancellablePromise<string>}
 */
export function AppEncryptCall(obj) {
    return $Call.ByID(3277595459, obj).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * AppExport 导出记录 list 为空数组导出全部
 * @param {number[]} list
 * @param {string} savePath
 * @returns {$CancellablePromise<string>}
 */
export function AppExport(list, savePath) {
    return $Call.ByID(2987767368, list, savePath);
}

/**
 * AppGenerateCode 生成代码
 * @param {number} Theology
 * @param {string} Language
 * @param {string} Module
 * @returns {$CancellablePromise<string>}
 */
export function AppGenerateCode(Theology, Language, Module) {
    return $Call.ByID(3583218012, Theology, Language, Module);
}

/**
 * AppGenerateCodeInterface 生成代码接口
 * @param {number} Theology
 * @returns {$CancellablePromise<$models.GenerateCodeInterface>}
 */
export function AppGenerateCodeInterface(Theology) {
    return $Call.ByID(2351258111, Theology).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function AppGetEditorFontSize() {
    return $Call.ByID(1706882767);
}

/**
 * AppGetGenerateCodeInterface 保存生成代码接口
 * @returns {$CancellablePromise<string>}
 */
export function AppGetGenerateCodeInterface() {
    return $Call.ByID(3241049747);
}

/**
 * @param {boolean} isDark
 * @returns {$CancellablePromise<void>}
 */
export function AppGetTheme(isDark) {
    return $Call.ByID(4018589343, isDark);
}

/**
 * AppImport 导入记录
 * @param {string} filePath
 * @returns {$CancellablePromise<[string, Session$0.Insert[]]>}
 */
export function AppImport(filePath) {
    return $Call.ByID(243131127, filePath).then(/** @type {($result: any) => any} */(($result) => {
        $result[1] = $$createType2($result[1]);
        return $result;
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function AppInsertDone() {
    return $Call.ByID(2029986351);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function AppIsSetPort() {
    return $Call.ByID(3304893681);
}

/**
 * AppResendRequest 重发请求
 * @param {number} id
 * @param {number} count
 * @param {number} BreakMode
 * @returns {$CancellablePromise<boolean>}
 */
export function AppResendRequest(id, count, BreakMode) {
    return $Call.ByID(538077910, id, count, BreakMode);
}

/**
 * AppSaveGenerateCodeInterface 保存生成代码接口
 * @param {string} code
 * @returns {$CancellablePromise<void>}
 */
export function AppSaveGenerateCodeInterface(code) {
    return $Call.ByID(3284561488, code);
}

/**
 * AppSaveRequestImg 保存请求图片
 * @param {number} Theology
 * @param {string} ImgType
 * @param {boolean} IsRequest
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function AppSaveRequestImg(Theology, ImgType, IsRequest, path) {
    return $Call.ByID(2557656839, Theology, ImgType, IsRequest, path);
}

/**
 * @param {number} size
 * @returns {$CancellablePromise<void>}
 */
export function AppSetEditorFontSize(size) {
    return $Call.ByID(3163254539, size);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function AppStartInsert() {
    return $Call.ByID(3249601771);
}

/**
 * @param {boolean} isSelect
 * @returns {$CancellablePromise<void>}
 */
export function AppStartSelectRequest(isSelect) {
    return $Call.ByID(141490183, isSelect);
}

/**
 * AppVersion 获取SDK版本信息
 * @returns {$CancellablePromise<string>}
 */
export function AppVersion() {
    return $Call.ByID(2676433910);
}

/**
 * ApplyHTTPSProtocol 保存并生效 HTTPS 协议/HTTP2 指纹/JA3（指纹在后续 HTTP 请求 ReplaceHttp 中按连接应用）。
 * @param {boolean | null} sendIsHTTP1
 * @param {string} protoJSON
 * @param {boolean | null} randomJa3
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function ApplyHTTPSProtocol(sendIsHTTP1, protoJSON, randomJa3) {
    return $Call.ByID(3895349038, sendIsHTTP1, protoJSON, randomJa3).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * AuthModeCreate 添加
 * @returns {$CancellablePromise<number>}
 */
export function AuthModeCreate() {
    return $Call.ByID(1378234546);
}

/**
 * @returns {$CancellablePromise<Config$0.Auth[]>}
 */
export function AuthModeList() {
    return $Call.ByID(99886754).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * AuthModeRemove 删除身份验证
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function AuthModeRemove(id) {
    return $Call.ByID(170895698, id);
}

/**
 * AuthModeSet 设置身份验证账号密码内容
 * @param {number} id
 * @param {string} User
 * @param {string} Pass
 * @returns {$CancellablePromise<void>}
 */
export function AuthModeSet(id, User, Pass) {
    return $Call.ByID(2785676270, id, User, Pass);
}

/**
 * @returns {$CancellablePromise<Config$0.AuthenticationInfo[]>}
 */
export function AuthenticationList() {
    return $Call.ByID(3911890539).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function AuthenticationRemove(id) {
    return $Call.ByID(3855582031, id);
}

/**
 * @param {number} id
 * @param {string} User
 * @param {string} Pass
 * @returns {$CancellablePromise<boolean>}
 */
export function AuthenticationUpdate(id, User, Pass) {
    return $Call.ByID(2707849090, id, User, Pass);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function CallKeys(id) {
    return $Call.ByID(1354225279, id);
}

/**
 * @param {string} name
 * @param {boolean} open
 * @param {string} args
 * @returns {$CancellablePromise<void>}
 */
export function CallTools(name, open, args) {
    return $Call.ByID(3292689070, name, open, args);
}

/**
 * CancelIEProxy 取消IE代理
 * @returns {$CancellablePromise<boolean>}
 */
export function CancelIEProxy() {
    return $Call.ByID(3823114457);
}

/**
 * ClearAllSession 删除全部
 * @returns {$CancellablePromise<number[]>}
 */
export function ClearAllSession() {
    return $Call.ByID(102063245).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * ClearAllSessionMessageIdArray 删除指定唯一ID下的全部数据流
 * @param {number} theology
 * @returns {$CancellablePromise<number[]>}
 */
export function ClearAllSessionMessageIdArray(theology) {
    return $Call.ByID(103651178, theology).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * ClipboardReadAll 获取剪辑版内容,成功返回空字符串
 * @returns {$CancellablePromise<string>}
 */
export function ClipboardReadAll() {
    return $Call.ByID(3141604526);
}

/**
 * ClipboardWriteAll 设置剪辑版内容,成功返回空字符串
 * @param {string} value
 * @returns {$CancellablePromise<string>}
 */
export function ClipboardWriteAll(value) {
    return $Call.ByID(604926353, value);
}

/**
 * CopySessionMessageIdArray 复制数据 CopyType 复制类型 MessageIdArray 要复制是消息ID
 * @param {number} theology
 * @param {string} CopyType
 * @param {number[]} MessageIdArray
 * @returns {$CancellablePromise<string>}
 */
export function CopySessionMessageIdArray(theology, CopyType, MessageIdArray) {
    return $Call.ByID(1741057441, theology, CopyType, MessageIdArray);
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function CreateAuthentication() {
    return $Call.ByID(502390283);
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function CreateProxyWay() {
    return $Call.ByID(3737908880);
}

/**
 * CreateReplaceBody 创建替换
 * @returns {$CancellablePromise<number>}
 */
export function CreateReplaceBody() {
    return $Call.ByID(4134719441);
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function CreateReplaceHost() {
    return $Call.ByID(2866976219);
}

/**
 * CreateRequestCert 创建请求证书
 * @returns {$CancellablePromise<number>}
 */
export function CreateRequestCert() {
    return $Call.ByID(708090026);
}

/**
 * @param {string} filePath
 * @returns {$CancellablePromise<string>}
 */
export function CustomToolsAdd(filePath) {
    return $Call.ByID(4221348890, filePath);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<boolean>}
 */
export function CustomToolsDel(id) {
    return $Call.ByID(2265591776, id);
}

/**
 * @returns {$CancellablePromise<Config$0.ToolsInfo[]>}
 */
export function CustomToolsList() {
    return $Call.ByID(2284949799).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * DefaultColor 恢复默认的配色方案
 * @param {boolean} IsDark
 * @returns {$CancellablePromise<void>}
 */
export function DefaultColor(IsDark) {
    return $Call.ByID(3110379455, IsDark);
}

/**
 * DelSessionMessageIdArray 删除指定 TCP/UDP/WSS 数据
 * @param {number} theology
 * @param {number[]} MessageIdArray
 * @returns {$CancellablePromise<number[]>}
 */
export function DelSessionMessageIdArray(theology, MessageIdArray) {
    return $Call.ByID(1359698511, theology, MessageIdArray).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {Config$0.DoHTTPRequestInfo} req
 * @returns {$CancellablePromise<string>}
 */
export function DoHTTPGenerateCode(req) {
    return $Call.ByID(1931183636, req);
}

/**
 * @param {Config$0.DoHTTPRequestInfo} req
 * @returns {$CancellablePromise<string>}
 */
export function DoHTTPRequest(req) {
    return $Call.ByID(3747649839, req);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function ExecCustomTools(id) {
    return $Call.ByID(2413018376, id);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function ExportCert(path) {
    return $Call.ByID(2312182955, path);
}

/**
 * @param {$models.FindInfo | null} info
 * @returns {$CancellablePromise<number[]>}
 */
export function FindSession(info) {
    return $Call.ByID(1008482784, info).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * FreeAllRequest 释放全部
 * @returns {$CancellablePromise<void>}
 */
export function FreeAllRequest() {
    return $Call.ByID(1412713557);
}

/**
 * GOOS 当前系统是否Windows
 * @returns {$CancellablePromise<boolean>}
 */
export function GOOS() {
    return $Call.ByID(768531895);
}

/**
 * GetAgGridDarkTheme 获取输入的暗色主题
 * @returns {$CancellablePromise<string>}
 */
export function GetAgGridDarkTheme() {
    return $Call.ByID(1973859942);
}

/**
 * GetAgGridLightTheme 获取输入的亮色主题
 * @returns {$CancellablePromise<string>}
 */
export function GetAgGridLightTheme() {
    return $Call.ByID(613808188);
}

/**
 * @returns {$CancellablePromise<Tools$0.ProcessesInfo[]>}
 */
export function GetAllProcessesList() {
    return $Call.ByID(271176589).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetAllStream 获取ws,tcp,udp,全部Stream
 * @param {number} Theology
 * @returns {$CancellablePromise<Session$0.UpdateSocketStream[]>}
 */
export function GetAllStream(Theology) {
    return $Call.ByID(3278228320, Theology).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @returns {$CancellablePromise<[boolean, boolean, boolean, boolean, number]>}
 */
export function GetBaseSettingsValue() {
    return $Call.ByID(421828982);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetColumnState() {
    return $Call.ByID(1160297364);
}

/**
 * GetError 获取错误信息
 * @returns {$CancellablePromise<string>}
 */
export function GetError() {
    return $Call.ByID(1670522013);
}

/**
 * @param {number} Theology
 * @param {boolean} getAllBody
 * @returns {$CancellablePromise<string>}
 */
export function GetHTTPRequestBody(Theology, getAllBody) {
    return $Call.ByID(1529364082, Theology, getAllBody).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * @param {number} Theology
 * @param {boolean} getAllBody
 * @returns {$CancellablePromise<string>}
 */
export function GetHTTPResponseBody(Theology, getAllBody) {
    return $Call.ByID(1489337542, Theology, getAllBody).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetHTTPSProto() {
    return $Call.ByID(1486529508);
}

/**
 * GetHTTPSession 根据唯一ID 获取HTTP消息内容
 * @param {number} Theology
 * @returns {$CancellablePromise<Session$0.HttpSession | null>}
 */
export function GetHTTPSession(Theology) {
    return $Call.ByID(2764261339, Theology).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetHomeTextMark 获取列表颜色标记
 * @returns {$CancellablePromise<string>}
 */
export function GetHomeTextMark() {
    return $Call.ByID(3253586676);
}

/**
 * GetIPV4InterfaceAdders 获取所有IPV4网卡IP
 * @returns {$CancellablePromise<string[]>}
 */
export function GetIPV4InterfaceAdders() {
    return $Call.ByID(2636619980).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * GetInterfaceOutRouterAdders 获取出口IP
 * @returns {$CancellablePromise<string>}
 */
export function GetInterfaceOutRouterAdders() {
    return $Call.ByID(292966176);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetKeys() {
    return $Call.ByID(3820515321);
}

/**
 * @param {boolean} IsDark
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetListColor(IsDark) {
    return $Call.ByID(575032280, IsDark).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetLocalServerPATH() {
    return $Call.ByID(2415905256);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetMustTcpRoles() {
    return $Call.ByID(1822771092);
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function GetMustTcpType() {
    return $Call.ByID(585351859);
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function GetPort() {
    return $Call.ByID(4103335178);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetProxyDns() {
    return $Call.ByID(2444539802);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetProxyRoles() {
    return $Call.ByID(1440161656);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetRandomJa3() {
    return $Call.ByID(1103213252);
}

/**
 * GetSendIsHTTP1 获取是否强制发送HTTP1.1请求
 * @returns {$CancellablePromise<boolean>}
 */
export function GetSendIsHTTP1() {
    return $Call.ByID(3938090362);
}

/**
 * GetSessionMessageBody 获取指定 TCP/UDP/WSS 字节数组 数据
 * @param {number} Theology
 * @param {number} MessageId
 * @returns {$CancellablePromise<string>}
 */
export function GetSessionMessageBody(Theology, MessageId) {
    return $Call.ByID(1030939398, Theology, MessageId).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * GetSocketFilter 获取  WS/UDP/TCP 过滤器
 * @param {number} theology
 * @returns {$CancellablePromise<string>}
 */
export function GetSocketFilter(theology) {
    return $Call.ByID(2120820618, theology);
}

/**
 * @param {boolean} newTour
 * @returns {$CancellablePromise<boolean>}
 */
export function GetTour(newTour) {
    return $Call.ByID(2862569039, newTour);
}

/**
 * @param {string} data
 * @returns {$CancellablePromise<string>}
 */
export function GoGetHex(data) {
    return $Call.ByID(3998741152, data);
}

/**
 * IsDark 设置当前是否选择暗色主题
 * @returns {$CancellablePromise<boolean>}
 */
export function IsDark() {
    return $Call.ByID(658768291);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsGetSelectRequest() {
    return $Call.ByID(606441778);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsLoadDevice() {
    return $Call.ByID(4276528585);
}

/**
 * ListSearch 设置主列表过滤器
 * @param {string} FilterJson
 * @returns {$CancellablePromise<number[]>}
 */
export function ListSearch(FilterJson) {
    return $Call.ByID(1148922567, FilterJson).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * LoadDevice true表示使用NFAPI驱动 如果为false 表示使用Proxifier
 * @param {number} mode
 * @returns {$CancellablePromise<boolean>}
 */
export function LoadDevice(mode) {
    return $Call.ByID(3235105853, mode);
}

/**
 * MCPDisable 关闭 MCP HTTP 桥。
 * @returns {$CancellablePromise<string>}
 */
export function MCPDisable() {
    return $Call.ByID(3619511515);
}

/**
 * MCPDocURL 返回 MCP 文档页 URL；服务未启用时为空。
 * @returns {$CancellablePromise<string>}
 */
export function MCPDocURL() {
    return $Call.ByID(2839039414);
}

/**
 * MCPEnable 启动 MCP HTTP 桥；port<=0 使用默认端口；成功返回空字符串。
 * @param {number} port
 * @returns {$CancellablePromise<string>}
 */
export function MCPEnable(port) {
    return $Call.ByID(17875766, port);
}

/**
 * MCPListOpsJSON 返回 MCP 桥能力目录 JSON（op 列表与 capabilities 说明）。
 * @returns {$CancellablePromise<string>}
 */
export function MCPListOpsJSON() {
    return $Call.ByID(3601920205);
}

/**
 * MCPStatusJSON 返回 MCP 桥状态（JSON 字符串）。
 * @returns {$CancellablePromise<string>}
 */
export function MCPStatusJSON() {
    return $Call.ByID(1756729541);
}

/**
 * McpFuncRes 获取 mcp 结果
 * @param {mcp$0.McpMsg} res
 * @returns {$CancellablePromise<void>}
 */
export function McpFuncRes(res) {
    return $Call.ByID(1915653471, res);
}

/**
 * @param {string} prompt
 * @returns {$CancellablePromise<string>}
 */
export function OpenSunnyFile(prompt) {
    return $Call.ByID(3696709260, prompt);
}

/**
 * @param {number} $0
 * @param {any[]} info
 * @returns {$CancellablePromise<void>}
 */
export function PrintScriptLog($0, ...info) {
    return $Call.ByID(2637329009, $0, info);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function ProcessAddName(name) {
    return $Call.ByID(3757552180, name);
}

/**
 * @param {number} pid
 * @returns {$CancellablePromise<void>}
 */
export function ProcessAddPid(pid) {
    return $Call.ByID(236451360, pid);
}

/**
 * @param {boolean} open
 * @param {boolean} StopNetwork
 * @returns {$CancellablePromise<void>}
 */
export function ProcessAny(open, StopNetwork) {
    return $Call.ByID(2967867366, open, StopNetwork);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function ProcessDelName(name) {
    return $Call.ByID(2056699882, name);
}

/**
 * @param {number} pid
 * @returns {$CancellablePromise<void>}
 */
export function ProcessDelPid(pid) {
    return $Call.ByID(4020576030, pid);
}

/**
 * @param {string} aa
 * @param {number} skip
 * @returns {$CancellablePromise<string>}
 */
export function ProtobufToJson(aa, skip) {
    return $Call.ByID(537388235, aa, skip);
}

/**
 * @returns {$CancellablePromise<Config$0.ProxyWayInfo[]>}
 */
export function ProxyWayList() {
    return $Call.ByID(3251954320).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function ProxyWayRemove(id) {
    return $Call.ByID(324847024, id);
}

/**
 * @param {number} id
 * @param {string} URL
 * @param {string} State
 * @param {string} Note
 * @returns {$CancellablePromise<boolean>}
 */
export function ProxyWayUpdate(id, URL, State, Note) {
    return $Call.ByID(2204700937, id, URL, State, Note);
}

/**
 * ReapplyEngineFromConfig 将当前 Config 中的引擎相关设置同步到运行中的 Sunny（MCP/UI 修改后调用）。
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function ReapplyEngineFromConfig() {
    return $Call.ByID(2681278770).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<Config$0.ReplaceBodyInfo[]>}
 */
export function ReplaceBodyList() {
    return $Call.ByID(4011958709).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function ReplaceBodyRemove(id) {
    return $Call.ByID(1958037689, id);
}

/**
 * @param {number} id
 * @param {string} Type
 * @param {string} Source
 * @param {string} Lod
 * @param {string} New
 * @param {string} Note
 * @param {string} state
 * @returns {$CancellablePromise<any>}
 */
export function ReplaceBodyUpdate(id, Type, Source, Lod, New, Note, state) {
    return $Call.ByID(225698152, id, Type, Source, Lod, New, Note, state);
}

/**
 * @returns {$CancellablePromise<Config$0.ReplaceHostInfo[]>}
 */
export function ReplaceHostList() {
    return $Call.ByID(3247463323).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function ReplaceHostRemove(id) {
    return $Call.ByID(20007679, id);
}

/**
 * @param {number} id
 * @param {string} Lod
 * @param {string} New
 * @param {string} Note
 * @returns {$CancellablePromise<boolean>}
 */
export function ReplaceHostUpdate(id, Lod, New, Note) {
    return $Call.ByID(281554706, id, Lod, New, Note);
}

/**
 * RequestCertGetCommonName 获取证书名称
 * @param {number} id
 * @returns {$CancellablePromise<string>}
 */
export function RequestCertGetCommonName(id) {
    return $Call.ByID(589821468, id);
}

/**
 * RequestCertRemove 删除证书
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function RequestCertRemove(id) {
    return $Call.ByID(3248922870, id);
}

/**
 * RequestCertSetFile 设置载入证书文件
 * @param {number} id
 * @param {string} role
 * @param {string} DoMain
 * @param {string} file
 * @param {string} pass
 * @param {string} note
 * @returns {$CancellablePromise<string>}
 */
export function RequestCertSetFile(id, role, DoMain, file, pass, note) {
    return $Call.ByID(3341316868, id, role, DoMain, file, pass, note);
}

/**
 * RequestList 获取全部列表
 * @returns {$CancellablePromise<Config$0.CertInfo[]>}
 */
export function RequestList() {
    return $Call.ByID(2377556936).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ResetALLConfig() {
    return $Call.ByID(1593269679);
}

/**
 * @param {Config$0.ToolsInfo} objInfo
 * @returns {$CancellablePromise<boolean>}
 */
export function SaveCustomTools(objInfo) {
    return $Call.ByID(1074446272, objInfo);
}

/**
 * @param {number} $0
 * @param {string} code
 * @returns {$CancellablePromise<void>}
 */
export function SaveScriptCode($0, code) {
    return $Call.ByID(2662134312, $0, code);
}

/**
 * @param {string} prompt
 * @returns {$CancellablePromise<string>}
 */
export function SaveSunnyFile(prompt) {
    return $Call.ByID(409579051, prompt);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ScriptLogInit() {
    return $Call.ByID(1863887056);
}

/**
 * SessionActiveSend 主动发送
 * @param {number} Theology
 * @param {boolean} isSendServer
 * @param {string} SendType
 * @param {number} wsType
 * @param {string} _bs
 * @returns {$CancellablePromise<string>}
 */
export function SessionActiveSend(Theology, isSendServer, SendType, wsType, _bs) {
    return $Call.ByID(2629591853, Theology, isSendServer, SendType, wsType, _bs);
}

/**
 * SetAuthMode 使用身份验证模式
 * @param {boolean} open
 * @returns {$CancellablePromise<void>}
 */
export function SetAuthMode(open) {
    return $Call.ByID(3162174792, open);
}

/**
 * SetBreakMode 设置断点模式
 * @param {number} working
 * @returns {$CancellablePromise<void>}
 */
export function SetBreakMode(working) {
    return $Call.ByID(205541003, working);
}

/**
 * @param {string} ColumnState
 * @returns {$CancellablePromise<void>}
 */
export function SetColumnState(ColumnState) {
    return $Call.ByID(3439809640, ColumnState);
}

/**
 * @param {boolean} stop
 * @returns {$CancellablePromise<void>}
 */
export function SetDeviceStopUpdate(stop) {
    return $Call.ByID(3840998266, stop);
}

/**
 * DisableCache 禁用浏览器缓存
 * @param {boolean} Disable
 * @returns {$CancellablePromise<void>}
 */
export function SetDisableCache(Disable) {
    return $Call.ByID(4261315479, Disable);
}

/**
 * DisableTCP 禁用TCP
 * @param {boolean} Disable
 * @returns {$CancellablePromise<void>}
 */
export function SetDisableTCP(Disable) {
    return $Call.ByID(389162262, Disable);
}

/**
 * DisableUDP 禁用UDP
 * @param {boolean} Disable
 * @returns {$CancellablePromise<void>}
 */
export function SetDisableUDP(Disable) {
    return $Call.ByID(2857493798, Disable);
}

/**
 * @param {string} proto
 * @returns {$CancellablePromise<void>}
 */
export function SetHTTPSProto(proto) {
    return $Call.ByID(731481032, proto);
}

/**
 * SetHomeTextMark 设置列表颜色标记
 * @param {string} TextMark
 * @returns {$CancellablePromise<void>}
 */
export function SetHomeTextMark(TextMark) {
    return $Call.ByID(3416042984, TextMark);
}

/**
 * SetIEProxy 设置IE代理
 * @returns {$CancellablePromise<boolean>}
 */
export function SetIEProxy() {
    return $Call.ByID(4000978765);
}

/**
 * SetInterfaceOutRouterAdders 设置出口IP
 * @param {string} ip
 * @returns {$CancellablePromise<void>}
 */
export function SetInterfaceOutRouterAdders(ip) {
    return $Call.ByID(2827274180, ip);
}

/**
 * SetIsDark 设置当前选择的是否暗色主题
 * @param {boolean} IsDark
 * @returns {$CancellablePromise<void>}
 */
export function SetIsDark(IsDark) {
    return $Call.ByID(1252175605, IsDark);
}

/**
 * @param {boolean} i
 * @returns {$CancellablePromise<void>}
 */
export function SetIsEditKeyDown(i) {
    return $Call.ByID(1936239572, i);
}

/**
 * @param {string} obj
 * @returns {$CancellablePromise<void>}
 */
export function SetKeys(obj) {
    return $Call.ByID(137324653, obj);
}

/**
 * LimitRequestSize 设置限制请求大小
 * @param {number} size
 * @returns {$CancellablePromise<void>}
 */
export function SetLimitRequestSize(size) {
    return $Call.ByID(1619520676, size);
}

/**
 * SetListColor 配置列表项颜色
 * @param {boolean} IsDark
 * @param {string} ColorID
 * @param {string} Color
 * @returns {$CancellablePromise<void>}
 */
export function SetListColor(IsDark, ColorID, Color) {
    return $Call.ByID(3558786916, IsDark, ColorID, Color);
}

/**
 * @param {number} Type
 * @param {string} Roles
 * @returns {$CancellablePromise<void>}
 */
export function SetMustTcpRoles(Type, Roles) {
    return $Call.ByID(1625757416, Type, Roles);
}

/**
 * @param {number} Port
 * @param {boolean} noStart
 * @returns {$CancellablePromise<string>}
 */
export function SetPort(Port, noStart) {
    return $Call.ByID(2328457798, Port, noStart);
}

/**
 * @param {string} dns
 * @returns {$CancellablePromise<void>}
 */
export function SetProxyDns(dns) {
    return $Call.ByID(1224380862, dns);
}

/**
 * @param {string} roles
 * @returns {$CancellablePromise<void>}
 */
export function SetProxyRoles(roles) {
    return $Call.ByID(3784858084, roles);
}

/**
 * @param {boolean} open
 * @returns {$CancellablePromise<void>}
 */
export function SetRandomJa3(open) {
    return $Call.ByID(2080467736, open);
}

/**
 * SetRequestNextBreakMode 设置断点模式
 * @param {number} Theology
 * @param {number} working
 * @returns {$CancellablePromise<void>}
 */
export function SetRequestNextBreakMode(Theology, working) {
    return $Call.ByID(12823753, Theology, working);
}

/**
 * @param {Session$0.HttpSession | null} req
 * @returns {$CancellablePromise<void>}
 */
export function SetSelectRequest(req) {
    return $Call.ByID(85683242, req);
}

/**
 * SetSendIsHTTP1 获取是否强制发送HTTP1.1请求
 * @param {boolean} value
 * @returns {$CancellablePromise<void>}
 */
export function SetSendIsHTTP1(value) {
    return $Call.ByID(1552691062, value);
}

/**
 * SetWorking 设置是否隐藏捕获数据
 * @param {boolean} working
 * @returns {$CancellablePromise<void>}
 */
export function SetWorking(working) {
    return $Call.ByID(452534664, working);
}

/**
 * Start 启动
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(3773833429);
}

/**
 * StreamSearch 设置 WS/UDP/TCP 过滤器
 * @param {number} Theology
 * @param {string} FilterJson
 * @returns {$CancellablePromise<number[]>}
 */
export function StreamSearch(Theology, FilterJson) {
    return $Call.ByID(3293252303, Theology, FilterJson).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * Theme 获取或应用主题
 * @param {boolean} isDark
 * @param {string} _type
 * @param {string} Theme
 * @returns {$CancellablePromise<string>}
 */
export function Theme(isDark, _type, Theme) {
    return $Call.ByID(396984080, isDark, _type, Theme);
}

/**
 * URLQueryEscape URL编码,失败返回空
 * @param {string} value
 * @returns {$CancellablePromise<string>}
 */
export function URLQueryEscape(value) {
    return $Call.ByID(259253583, value);
}

/**
 * URLQueryUnescape URL解码,失败返回空
 * @param {string} value
 * @returns {$CancellablePromise<string>}
 */
export function URLQueryUnescape(value) {
    return $Call.ByID(2479663392, value).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * UpdateHttpRequest 更新 HTTP 请求（MCP / UI 共用）。
 * @param {number} Theology
 * @param {Session$0.HttpSessionRequest | null} req
 * @returns {$CancellablePromise<void>}
 */
export function UpdateHttpRequest(Theology, req) {
    return $Call.ByID(2776416747, Theology, req);
}

/**
 * UpdateHttpResponse 更新 HTTP 响应（MCP / UI 共用）。
 * @param {number} Theology
 * @param {Session$0.HttpSessionResponse | null} req
 * @returns {$CancellablePromise<void>}
 */
export function UpdateHttpResponse(Theology, req) {
    return $Call.ByID(3251823209, Theology, req);
}

/**
 * UpdateNote 更新注释信息
 * @param {number} Theology
 * @param {string} Note
 * @returns {$CancellablePromise<boolean>}
 */
export function UpdateNote(Theology, Note) {
    return $Call.ByID(245577482, Theology, Note);
}

// Private type creation functions
const $$createType0 = $models.GenerateCodeInterface.createFrom;
const $$createType1 = Session$0.Insert.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = Config$0.Auth.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = Config$0.AuthenticationInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($Create.Any);
const $$createType9 = Config$0.ToolsInfo.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = Tools$0.ProcessesInfo.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = Session$0.UpdateSocketStream.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = Session$0.HttpSession.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = $Create.Array($Create.Any);
const $$createType18 = $Create.Map($Create.Any, $Create.Any);
const $$createType19 = Config$0.ProxyWayInfo.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = Config$0.ReplaceBodyInfo.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = Config$0.ReplaceHostInfo.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = Config$0.CertInfo.createFrom;
const $$createType26 = $Create.Array($$createType25);
