// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as http$0 from "../../github.com/qtgolang/SunnyNet/src/http/models.js";

export class FindInfo {
    /**
     * Creates a new FindInfo instance.
     * @param {Partial<FindInfo>} [$$source = {}] - The source object to create the FindInfo.
     */
    constructor($$source = {}) {
        if (!("Theology" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Theology"] = 0;
        }
        if (!("Options" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Options"] = "";
        }
        if (!("Value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Value"] = "";
        }
        if (!("Type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Type"] = "";
        }
        if (!("Range" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Range"] = "";
        }
        if (!("Color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Color"] = "";
        }
        if (!("ProtoSkip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ProtoSkip"] = "";
        }
        if (!("Action" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Action"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FindInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FindInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FindInfo(/** @type {Partial<FindInfo>} */($$parsedSource));
    }
}

export class GenerateCodeInterface {
    /**
     * Creates a new GenerateCodeInterface instance.
     * @param {Partial<GenerateCodeInterface>} [$$source = {}] - The source object to create the GenerateCodeInterface.
     */
    constructor($$source = {}) {
        if (!("Path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Path"] = "";
        }
        if (!("URL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["URL"] = "";
        }
        if (!("Header" in $$source)) {
            /**
             * @member
             * @type {http$0.Header}
             */
            this["Header"] = {};
        }
        if (!("IP" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["IP"] = "";
        }
        if (!("Method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Method"] = "";
        }
        if (!("Body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerateCodeInterface instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GenerateCodeInterface}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField5_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Header" in $$parsedSource) {
            $$parsedSource["Header"] = $$createField2_0($$parsedSource["Header"]);
        }
        if ("Body" in $$parsedSource) {
            $$parsedSource["Body"] = $$createField5_0($$parsedSource["Body"]);
        }
        return new GenerateCodeInterface(/** @type {Partial<GenerateCodeInterface>} */($$parsedSource));
    }
}

// Private type creation functions
var $$createType0 = /** @type {(...args: any[]) => any} */(function $$initCreateType0(...args) {
    if ($$createType0 === $$initCreateType0) {
        $$createType0 = $$createType2;
    }
    return $$createType0(...args);
});
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Map($Create.Any, $$createType1);
